// nameGenerator

const adjectivesAnimals = [
  'furry',
  'ferocious',
  'dangerous',
  'poisonous',
  'tame',
  'agile',
  'clever',
  'aggressive',
  'tiny',
  'domestic',
  'wild',
  'herbivorous',
  'carnivorous',
  'Adorable',
  'Aggressive',
  'Agile',
  'Beautiful',
  'Bossy',
  'Candid',
  'Carnivorous',
  'Clever',
  'Cold',
  'Cold-Blooded',
  'Colorful',
  'Cuddly',
  'Curious',
  'Cute',
  'Dangerous',
  'Deadly',
  'Domestic',
  'Dominant',
  'Energetic',
  'Fast',
  'Feisty',
  'Ferocious',
  'Fierce',
  'Fluffy',
  'Friendly',
  'Furry',
  'Fuzzy',
  'Grumpy',
  'Hairy',
  'Heavy',
  'Herbivorous',
  'Jealous',
  'Large',
  'Lazy',
  'Loud',
  'Lovable',
  'Loving',
  'Malicious',
  'Maternal',
  'Mean',
  'Messy',
  'Nocturnal',
  'Noisy',
  'Nosy',
  'Picky',
  'Playful',
  'Poisonous',
  'Quick',
  'Rough',
  'Sassy',
  'Scaly',
  'Short',
  'Shy',
  'Slimy',
  'Slow',
  'Small',
  'Smart',
  'Smelly',
  'Soft',
  'Spikey',
  'Stinky',
  'Strong',
  'Stubborn',
  'Submissive',
  'Tall',
  'Tame',
  'Tenacious',
  'Territorial',
  'Tiny',
  'Vicious',
  'Warm',
  'Wild',
];

const adjectivesAnonymous = [
  'mysterious',
  'cryptic',
  'curious',
  'enigmatic',
  'inexplicable',
  'inscrutable',
  'mystifying',
  'obscure',
  'perplexing',
  'puzzling',
  'secretive',
  'strange',
  'eldritch',
  'unknown',
  'anonymous',
  'unidentified',
  'nameless',
  'unnamed',
  'unfamiliar',
  'incognito',
  'unspecified',
  'concealed',
  'distant',
  'exotic',
  'remote',
  'unsung',
  'untold',
  'undubbed',
  'unsigned',
  'unrevealed',
  'unmarked',
  'pseudonymous',
  'unusual',
  'intangible',
  'untraceable',
  'impenetrable',
  'esoteric',
  'recondite',
  'unfathomable',
  'bewildering',
  'labyrinthine',
  'muddled',
  'paradoxical',
  'perplexing',
  'puzzling',
  'baffling',
  'nondescript'
];

const adjectivesConcepts = [
  'unprecedented',
  'newfangled',
  'dangerous',
  'introspective',
  'brilliant',
  'notional',
  'clever',
  'weird',
  'audacious',
  'theoretical',
  'dynamic',
  'indeterminate',
  'puzzling',
  'philophical',
  'tenuous',
  'unknowable',
  'Beautiful',
  'frightening',
  'Candid',
  'original',
  'Clever',
  'fleeting',
  'unconvential',
  'Colorful',
  'incontrivertable',
  'complex',
  'mathematical',
  'workable',
  'delightful',
  'Non-Coporeal',
  'scietific',
  'Energetic',
  'dubious',
  'pragmatic',
  'probabilistic',
  'monolithic',
  'nonsensical',
  'comprehensive',
  'unabiguous',
  'poetical',
  'operational',
  'meaningless',
  'lunatic',
  'fascinating',
  'technological',
  'fundamental',
  'strategic',
  'transcendental',
  'objective',
  'awesome',
  'Self-Contained',
  'unimaginable',
  'suprising',
  'modern',
  'Extradimensional',
  'universal',
  'alien',
  'intellectual',
  'misanthropic',
  'problematic',
  'remarkable',
  'fashionable',
  'startling',
  'interesting',
  'kooky',
  'incompatible',
  'schematic',
  'relativistic',
  'earthshaking',
  'reactionary',
  'einsteinian',
  'straightforward',
  'ludricrous',
  'anomalous',
  'elusive',
  'aerodynamic',
  'irrational',
  'amorphous',
  'nebulous',
  'dangerous',
  'clever',
  'tiny',
  'wild',
  'Beautiful',
  'Clever',
  'Colorful',
  'Curious',
  'Heavy',
  'Large',
  'Malicious',
  'Playful',
];

const nounsAnimals = [
  'Aardvark',
  'Albatross',
  'Alligator',
  'Alpaca',
  'Ant',
  'Anteater',
  'Antelope',
  'Ape',
  'Armadillo',
  'Donkey',
  'Baboon',
  'Badger',
  'Barracuda',
  'Bat',
  'Bear',
  'Beaver',
  'Bee',
  'Bison',
  'Boar',
  'Buffalo',
  'Butterfly',
  'Camel',
  'Capybara',
  'Caribou',
  'Cassowary',
  'Cat',
  'Caterpillar',
  'Cattle',
  'Chamois',
  'Cheetah',
  'Chicken',
  'Chimpanzee',
  'Chinchilla',
  'Chough',
  'Clam',
  'Cobra',
  'Cockroach',
  'Cod',
  'Cormorant',
  'Coyote',
  'Crab',
  'Crane',
  'Crocodile',
  'Crow',
  'Curlew',
  'Deer',
  'Dinosaur',
  'Dog',
  'Dogfish',
  'Dolphin',
  'Dotterel',
  'Dove',
  'Dragonfly',
  'Duck',
  'Dugong',
  'Dunlin',
  'Eagle',
  'Echidna',
  'Eel',
  'Eland',
  'Elephant',
  'Elk',
  'Emu',
  'Falcon',
  'Ferret',
  'Finch',
  'Fish',
  'Flamingo',
  'Fly',
  'Fox',
  'Frog',
  'Gaur',
  'Gazelle',
  'Gerbil',
  'Giraffe',
  'Gnat',
  'Gnu',
  'Goat',
  'Goldfinch',
  'Goldfish',
  'Goose',
  'Gorilla',
  'Goshawk',
  'Grasshopper',
  'Grouse',
  'Guanaco',
  'Gull',
  'Hamster',
  'Hare',
  'Hawk',
  'Hedgehog',
  'Heron',
  'Herring',
  'Hippopotamus',
  'Hornet',
  'Horse',
  'Human',
  'Hummingbird',
  'Hyena',
  'Ibex',
  'Ibis',
  'Jackal',
  'Jaguar',
  'Jay',
  'Jellyfish',
  'Kangaroo',
  'Kingfisher',
  'Koala',
  'Kookabura',
  'Kouprey',
  'Kudu',
  'Lapwing',
  'Lark',
  'Lemur',
  'Leopard',
  'Lion',
  'Llama',
  'Lobster',
  'Locust',
  'Loris',
  'Louse',
  'Lyrebird',
  'Magpie',
  'Mallard',
  'Manatee',
  'Mandrill',
  'Mantis',
  'Marten',
  'Meerkat',
  'Mink',
  'Mole',
  'Mongoose',
  'Monkey',
  'Moose',
  'Mosquito',
  'Mouse',
  'Mule',
  'Narwhal',
  'Newt',
  'Nightingale',
  'Octopus',
  'Okapi',
  'Opossum',
  'Oryx',
  'Ostrich',
  'Otter',
  'Owl',
  'Oyster',
  'Panther',
  'Parrot',
  'Partridge',
  'Peafowl',
  'Pelican',
  'Penguin',
  'Pheasant',
  'Pig',
  'Pigeon',
  'Pony',
  'Porcupine',
  'Porpoise',
  'Quail',
  'Quelea',
  'Quetzal',
  'Rabbit',
  'Raccoon',
  'Rail',
  'Ram',
  'Rat',
  'Raven',
  'Red deer',
  'Red panda',
  'Reindeer',
  'Rhinoceros',
  'Rook',
  'Salamander',
  'Salmon',
  'Sand Dollar',
  'Sandpiper',
  'Sardine',
  'Scorpion',
  'Seahorse',
  'Seal',
  'Shark',
  'Sheep',
  'Shrew',
  'Skunk',
  'Snail',
  'Snake',
  'Sparrow',
  'Spider',
  'Spoonbill',
  'Squid',
  'Squirrel',
  'Starling',
  'Stingray',
  'Stinkbug',
  'Stork',
  'Swallow',
  'Swan',
  'Tapir',
  'Tarsier',
  'Termite',
  'Tiger',
  'Toad',
  'Trout',
  'Turkey',
  'Turtle',
  'Viper',
  'Vulture',
  'Wallaby',
  'Walrus',
  'Wasp',
  'Weasel',
  'Whale',
  'Wildcat',
  'Wolf',
  'Wolverine',
  'Wombat',
  'Woodcock',
  'Woodpecker',
  'Worm',
  'Wren',
  'Yak',
  'Zebra',
];
const nounsAnimalAvatars = [
  {
    name: 'parrot',
    url: 'avatar/svg/001-parrot.svg',
  },
  {
    name: 'penguin',
    url: 'avatar/svg/002-penguin.svg',
  },
  {
    name: 'giraffe',
    url: 'avatar/svg/003-giraffe.svg',
  },
  {
    name: 'bear',
    url: 'avatar/svg/004-bear.svg',
  },
  {
    name: 'puffer Fish',
    url: 'avatar/svg/005-puffer-fish.svg',
  },
  {
    name: 'sloth',
    url: 'avatar/svg/006-sloth.svg',
  },
  {
    name: 'gorilla',
    url: 'avatar/svg/007-gorilla.svg',
  },
  {
    name: 'fox',
    url: 'avatar/svg/008-fox.svg',
  },
  {
    name: 'zebra',
    url: 'avatar/svg/009-zebra.svg',
  },
  {
    name: 'bat',
    url: 'avatar/svg/010-bat.svg',
  },
  {
    name: 'owl',
    url: 'avatar/svg/011-owl.svg',
  },
  {
    name: 'crab',
    url: 'avatar/svg/012-crab.svg',
  },
  {
    name: 'llama',
    url: 'avatar/svg/013-llama.svg',
  },
  {
    name: 'snake',
    url: 'avatar/svg/014-snake.svg',
  },
  {
    name: 'wolf',
    url: 'avatar/svg/015-wolf.svg',
  },
  {
    name: 'lion',
    url: 'avatar/svg/016-lion.svg',
  },
  {
    name: 'goat',
    url: 'avatar/svg/017-goat.svg',
  },
  {
    name: 'rabbit',
    url: 'avatar/svg/018-rabbit.svg',
  },
  {
    name: 'ferret',
    url: 'avatar/svg/019-ferret.svg',
  },
  {
    name: 'mouse',
    url: 'avatar/svg/020-mouse.svg',
  },
  {
    name: 'turtle',
    url: 'avatar/svg/021-turtle.svg',
  },
  {
    name: 'hen',
    url: 'avatar/svg/022-hen.svg',
  },
  {
    name: 'pig',
    url: 'avatar/svg/023-pig.svg',
  },
  {
    name: 'hedgehog',
    url: 'avatar/svg/024-hedgehog.svg',
  },
  {
    name: 'walrus',
    url: 'avatar/svg/025-walrus.svg',
  },
  {
    name: 'skunk',
    url: 'avatar/svg/026-skunk.svg',
  },
  {
    name: 'frog',
    url: 'avatar/svg/027-frog.svg',
  },
  {
    name: 'chameleon',
    url: 'avatar/svg/028-chameleon.svg',
  },
  {
    name: 'squirrel',
    url: 'avatar/svg/029-squirrel.svg',
  },
  {
    name: 'rhino',
    url: 'avatar/svg/030-rhino.svg',
  },
  {
    name: 'ostrich',
    url: 'avatar/svg/031-ostrich.svg',
  },
  {
    name: 'hippopotamus',
    url: 'avatar/svg/032-hippopotamus.svg',
  },
  {
    name: 'koala',
    url: 'avatar/svg/033-koala.svg',
  },
  {
    name: 'camel',
    url: 'avatar/svg/034-camel.svg',
  },
  {
    name: 'beaver',
    url: 'avatar/svg/035-beaver.svg',
  },
  {
    name: 'dog',
    url: 'avatar/svg/036-dog.svg',
  },
  {
    name: 'turkey',
    url: 'avatar/svg/037-turkey.svg',
  },
  {
    name: 'deer',
    url: 'avatar/svg/038-deer.svg',
  },
  {
    name: 'cow',
    url: 'avatar/svg/039-cow.svg',
  },
  {
    name: 'elephant',
    url: 'avatar/svg/040-elephant.svg',
  },
  {
    name: 'chicken',
    url: 'avatar/svg/041-chicken.svg',
  },
  {
    name: 'duck',
    url: 'avatar/svg/042-duck.svg',
  },
  {
    name: 'wild Boar',
    url: 'avatar/svg/043-wild-boar.svg',
  },
  {
    name: 'bee',
    url: 'avatar/svg/044-bee.svg',
  },
  {
    name: 'horse',
    url: 'avatar/svg/045-horse.svg',
  },
  {
    name: 'sheep',
    url: 'avatar/svg/046-sheep.svg',
  },
  {
    name: 'panda',
    url: 'avatar/svg/047-panda.svg',
  },
  {
    name: 'monkey',
    url: 'avatar/svg/048-monkey.svg',
  },
  {
    name: 'cat',
    url: 'avatar/svg/049-cat.svg',
  },
  {
    name: 'octopus',
    url: 'avatar/svg/050-octopus.svg',
  },
];

const nounsConcepts = [
  'concept',
  'notion',
  'philosophy',
  'abstraction',
  'conception',
  'hypothesis',
  'principle',
  'construct',
  'model',
  'design',
  'ontology',
  'approach',
  'vision',
  'aspect',
  'paradigm',
  'theme',
  'element',
  'metaphor',
  'brainwave',
  'supposition',
  'intellection',
  'consideration',
  'brainchild',
  'view',
  'thought',
  'perception',
  'proof',
  'document',
  'program',
  'method',
  'mode',
  'Modus Operandi',
  'procedure',
  'technique',
  'theorem',
  'tenet',
  'precept',
  'postulate',
  'paradox',
  'doctrine',
  'credo',
  'assumption',
  'explanation',
  'dream',
  'interpretation',
  'inkling',
  'picture',
  'visualization',
  'plan',
  'representation',
  'speculation',
  'version',
  'rationale',
  'generalization',
  'attribute',
  'creation',
  'example',
  'structure',
  'universality',
  'fundamental',
  'definition',
  'embodiment',
  'instance',
  'predicate',
  'figment',
  'ethos',
  'strategy',
  'prototype',
  'misnomer',
  'methodology',
  'formulation',
  'schema',
  'gestalt',
  'charter',
  'information',
  'analysis',
  'representation',
  'communique',
  'theory',
];


const util = {
  capitalizeFirstLetter: function (string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  },

  aRandom: function (length) {
    return Math.floor(Math.random() * length);
  },
};

const randomAnimal = function () {
  const adjective = adjectivesAnimals[util.aRandom(adjectivesAnimals.length)];
  const noun = nounsAnimals[util.aRandom(nounsAnimals.length)];
  return `${util.capitalizeFirstLetter(adjective)} ${util.capitalizeFirstLetter(noun)}`;
};

const anonymousAnimal = function () {
  const adjective = adjectivesAnonymous[util.aRandom(adjectivesAnonymous.length)];
  const noun = nounsAnimals[util.aRandom(nounsAnimals.length)];
  return `${util.capitalizeFirstLetter(adjective)} ${util.capitalizeFirstLetter(noun)}`;
};

const anonymousAnimalAvatar = function (urlPrefix = './') {
  const adjective = adjectivesAnonymous[util.aRandom(adjectivesAnonymous.length)];
  const noun = nounsAnimalAvatars[util.aRandom(nounsAnimalAvatars.length)];
  return {
    name: `${util.capitalizeFirstLetter(adjective)} ${util.capitalizeFirstLetter(noun.name)}`,
    url: `${urlPrefix}${noun.url}`,
  };
};

const randomConcept = function () {
  const adjective = adjectivesConcepts[util.aRandom(adjectivesConcepts.length)];
  const noun = nounsConcepts[util.aRandom(nounsConcepts.length)];
  return `${util.capitalizeFirstLetter(adjective)} ${util.capitalizeFirstLetter(noun)}`;
};

export {
  randomAnimal,
  anonymousAnimal,
  anonymousAnimalAvatar,
  randomConcept
};
